configure now enforces HDF5 to be 1.4.X
git-svn-id: https://hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/rhdf5@5587 bc3139a8-67e5-0310-9ffc-ced21a209358

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 1.2 .
+# From configure.in Revision: 1.3 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52.
 #
@@ -1987,6 +1987,61 @@ echo "${ECHO_T}failed" >&6
 echo "$as_me: error: please specify a valid hdf5 installation with --with-hdf5=DIR" >&2;}
    { (exit 1); exit 1; }; }
 	fi
+
+echo "$as_me:1991: checking for hdf5 version 1.4" >&5
+echo $ECHO_N "checking for hdf5 version 1.4... $ECHO_C" >&6
+LIBS="$LIBS -lhdf5"
+if test "${ac_cv_working_hdf5_version+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test "$cross_compiling" = yes; then
+  ac_cv_working_hdf5_version=cross
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line 2001 "configure"
+#include "confdefs.h"
+#include <hdf5.h>
+
+int main(void) {
+        unsigned maj, min, rel;
+
+        H5get_libversion(&maj, &min, &rel);
+
+        if ((maj == 1)&&(min==4))
+           exit(0);
+        else
+           exit(1);
+}
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:2017: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:2020: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:2022: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:2025: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_working_hdf5_version=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_working_hdf5_version=no
+fi
+rm -f core core.* *.core conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+fi
+
+echo "$as_me:2038: result: $ac_cv_working_hdf5_version" >&5
+echo "${ECHO_T}$ac_cv_working_hdf5_version" >&6
+if test x$ac_cv_working_hdf5_version != "xyes"; then
+	{ { echo "$as_me:2041: error: HDF5 installation must be version 1.4.x" >&5
+echo "$as_me: error: HDF5 installation must be version 1.4.x" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 fi
 
 ac_config_files="$ac_config_files src/Makevars"
@@ -2099,7 +2154,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:2102: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:2157: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -2266,7 +2321,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:2269: error: ambiguous option: $1
+    { { echo "$as_me:2324: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -2285,7 +2340,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:2288: error: unrecognized option: $1
+  -*) { { echo "$as_me:2343: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -2321,7 +2376,7 @@ do
   case "$ac_config_target" in
   # Handling of arguments.
   "src/Makevars" ) CONFIG_FILES="$CONFIG_FILES src/Makevars" ;;
-  *) { { echo "$as_me:2324: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:2379: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -2520,7 +2575,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:2523: creating $ac_file" >&5
+    { echo "$as_me:2578: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -2538,7 +2593,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:2541: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:2596: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -2551,7 +2606,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:2554: error: cannot find input file: $f" >&5
+           { { echo "$as_me:2609: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
