Mac OSX Fink HDF5 check in configure
git-svn-id: file:///home/git/hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/rhdf5@1460 bc3139a8-67e5-0310-9ffc-ced21a209358

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision.
+# From configure.in Revision: 1.2 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52.
 #
@@ -629,7 +629,7 @@ Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
  --with-hdf5=DIR root directory of hdf5 installation defaults to
-	/usr/local or /usr if not found in /usr/local
+	/usr/local or /usr if not found in /usr/local and finally /sw
 
 Some influential environment variables:
   CC          C compiler command
@@ -1843,6 +1843,10 @@ echo "${ECHO_T}yes" >&6
 	if test ! -f "${HDF5_HOME}/include/hdf5.h"
 	then
 		HDF5_HOME="/usr"
+		if test ! -f "${HDF5_HOME}/include/hdf5.h"
+		then
+			HDF5_HOME="/sw"
+		fi
 	fi
 
 fi;
@@ -1860,7 +1864,7 @@ ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
-	echo "$as_me:1863: checking for H5Fopen in -lhdf5" >&5
+	echo "$as_me:1867: checking for H5Fopen in -lhdf5" >&5
 echo $ECHO_N "checking for H5Fopen in -lhdf5... $ECHO_C" >&6
 if test "${ac_cv_lib_hdf5_H5Fopen+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1868,7 +1872,7 @@ else
   ac_check_lib_save_LIBS=$LIBS
 LIBS="-lhdf5  $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
-#line 1871 "configure"
+#line 1875 "configure"
 #include "confdefs.h"
 
 /* Override any gcc2 internal prototype to avoid an error.  */
@@ -1887,16 +1891,16 @@ H5Fopen ();
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:1890: \"$ac_link\"") >&5
+if { (eval echo "$as_me:1894: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:1893: \$? = $ac_status" >&5
+  echo "$as_me:1897: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:1896: \"$ac_try\"") >&5
+  { (eval echo "$as_me:1900: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:1899: \$? = $ac_status" >&5
+  echo "$as_me:1903: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   ac_cv_lib_hdf5_H5Fopen=yes
 else
@@ -1907,7 +1911,7 @@ fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:1910: result: $ac_cv_lib_hdf5_H5Fopen" >&5
+echo "$as_me:1914: result: $ac_cv_lib_hdf5_H5Fopen" >&5
 echo "${ECHO_T}$ac_cv_lib_hdf5_H5Fopen" >&6
 if test $ac_cv_lib_hdf5_H5Fopen = yes; then
   hdf5_cv_libhdf5=yes
@@ -1915,23 +1919,23 @@ else
   hdf5_cv_libhdf5=no
 fi
 
-	echo "$as_me:1918: checking for hdf5.h" >&5
+	echo "$as_me:1922: checking for hdf5.h" >&5
 echo $ECHO_N "checking for hdf5.h... $ECHO_C" >&6
 if test "${ac_cv_header_hdf5_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >conftest.$ac_ext <<_ACEOF
-#line 1924 "configure"
+#line 1928 "configure"
 #include "confdefs.h"
 #include <hdf5.h>
 _ACEOF
-if { (eval echo "$as_me:1928: \"$ac_cpp conftest.$ac_ext\"") >&5
+if { (eval echo "$as_me:1932: \"$ac_cpp conftest.$ac_ext\"") >&5
   (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
   ac_status=$?
   egrep -v '^ *\+' conftest.er1 >conftest.err
   rm -f conftest.er1
   cat conftest.err >&5
-  echo "$as_me:1934: \$? = $ac_status" >&5
+  echo "$as_me:1938: \$? = $ac_status" >&5
   (exit $ac_status); } >/dev/null; then
   if test -s conftest.err; then
     ac_cpp_err=$ac_c_preproc_warn_flag
@@ -1950,7 +1954,7 @@ else
 fi
 rm -f conftest.err conftest.$ac_ext
 fi
-echo "$as_me:1953: result: $ac_cv_header_hdf5_h" >&5
+echo "$as_me:1957: result: $ac_cv_header_hdf5_h" >&5
 echo "${ECHO_T}$ac_cv_header_hdf5_h" >&6
 if test $ac_cv_header_hdf5_h = yes; then
   hdf5_cv_hdf5_h=yes
@@ -1966,20 +1970,20 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 	if test "$hdf5_cv_libhdf5" = "yes" -a "$hdf5_cv_hdf5_h" = "yes"
 	then
-		echo "$as_me:1969: checking hdf5 in ${HDF5_HOME}" >&5
+		echo "$as_me:1973: checking hdf5 in ${HDF5_HOME}" >&5
 echo $ECHO_N "checking hdf5 in ${HDF5_HOME}... $ECHO_C" >&6
 		PKG_LIBS="${PKG_LIBS} -L${HDF5_HOME}/lib -lhdf5"
 		PKG_CPPFLAGS="${PKG_CPPFLAGS} -L${HDF5_HOME}/include"
-		echo "$as_me:1973: result: ok" >&5
+		echo "$as_me:1977: result: ok" >&5
 echo "${ECHO_T}ok" >&6
 	else
-		echo "$as_me:1976: checking hdf5 in ${HDF5_HOME}" >&5
+		echo "$as_me:1980: checking hdf5 in ${HDF5_HOME}" >&5
 echo $ECHO_N "checking hdf5 in ${HDF5_HOME}... $ECHO_C" >&6
 		LDFLAGS="${HDF5_OLD_LDFLAGS}"
 		CPPFLAGS="${HDF5_OLD_CPPFLAGS}"
-		echo "$as_me:1980: result: failed" >&5
+		echo "$as_me:1984: result: failed" >&5
 echo "${ECHO_T}failed" >&6
-		{ { echo "$as_me:1982: error: please specify a valid hdf5 installation with --with-hdf5=DIR" >&5
+		{ { echo "$as_me:1986: error: please specify a valid hdf5 installation with --with-hdf5=DIR" >&5
 echo "$as_me: error: please specify a valid hdf5 installation with --with-hdf5=DIR" >&2;}
    { (exit 1); exit 1; }; }
 	fi
@@ -2095,7 +2099,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:2098: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:2102: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -2262,7 +2266,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:2265: error: ambiguous option: $1
+    { { echo "$as_me:2269: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -2281,7 +2285,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:2284: error: unrecognized option: $1
+  -*) { { echo "$as_me:2288: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -2317,7 +2321,7 @@ do
   case "$ac_config_target" in
   # Handling of arguments.
   "src/Makevars" ) CONFIG_FILES="$CONFIG_FILES src/Makevars" ;;
-  *) { { echo "$as_me:2320: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:2324: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -2516,7 +2520,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:2519: creating $ac_file" >&5
+    { echo "$as_me:2523: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -2534,7 +2538,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:2537: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:2541: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -2547,7 +2551,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:2550: error: cannot find input file: $f" >&5
+           { { echo "$as_me:2554: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
